# Generated by Django 6.0.3 on 2026-04-03 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(default='2024-2025', max_length=10)),
                ('number', models.CharField(choices=[('1', '1er Trimestre'), ('2', '2ème Trimestre'), ('3', '3ème Trimestre')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['school_year', 'number'],
                'unique_together': {('school_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weighted_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classroom')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.trimester')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('student', 'subject', 'classroom', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('class_size', models.IntegerField(blank=True, null=True)),
                ('class_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lowest_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conduct_grade', models.CharField(choices=[('A+', 'Très bien'), ('A', 'Bien'), ('B', 'Assez bien'), ('C', 'Passable'), ('D', 'Insuffisant')], default='B', max_length=2)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('absences_total', models.IntegerField(default=0)),
                ('absences_justified', models.IntegerField(default=0)),
                ('lates_total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classroom')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.trimester')),
            ],
            options={
                'ordering': ['-trimester__school_year', 'trimester__number'],
                'unique_together': {('student', 'classroom', 'trimester')},
            },
        ),
    ]
